/**
 * Sulfur backend
 * El login exitoso de UserService devuelve un Colaborador con un campo \"token\". Dicho token se debe incluir como header de las llamadas del resto de las operaciones de cada servicio.
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class Cargo {
    id?: number;

    nombre: string;

    codigo: string;

    precioHora: number;

    public constructor(c: Cargo) {
        this.id = c.id;
        this.nombre = c.nombre;
        this.codigo = c.codigo;
        this.precioHora = c.precioHora;
    }
}
