/**
 * Sulfur backend
 * El login exitoso de UserService devuelve un Colaborador con un campo \"token\". Dicho token se debe incluir como header de las llamadas del resto de las operaciones de cada servicio.
 *
 * OpenAPI spec version: 1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface LocalDate {
    year?: number;

    month?: LocalDate.MonthEnum;

    dayOfYear?: number;

    dayOfWeek?: LocalDate.DayOfWeekEnum;

    leapYear?: boolean;

    dayOfMonth?: number;

    monthValue?: number;

    era?: models.Era;

    chronology?: models.IsoChronology;

}
export namespace LocalDate {
    export enum MonthEnum {
        JANUARY = <any> 'JANUARY',
        FEBRUARY = <any> 'FEBRUARY',
        MARCH = <any> 'MARCH',
        APRIL = <any> 'APRIL',
        MAY = <any> 'MAY',
        JUNE = <any> 'JUNE',
        JULY = <any> 'JULY',
        AUGUST = <any> 'AUGUST',
        SEPTEMBER = <any> 'SEPTEMBER',
        OCTOBER = <any> 'OCTOBER',
        NOVEMBER = <any> 'NOVEMBER',
        DECEMBER = <any> 'DECEMBER'
    }
    export enum DayOfWeekEnum {
        MONDAY = <any> 'MONDAY',
        TUESDAY = <any> 'TUESDAY',
        WEDNESDAY = <any> 'WEDNESDAY',
        THURSDAY = <any> 'THURSDAY',
        FRIDAY = <any> 'FRIDAY',
        SATURDAY = <any> 'SATURDAY',
        SUNDAY = <any> 'SUNDAY'
    }
}
